# Dependencies
markdown:         rdiscount
pygments:         true

# Permalinks
permalink:        pretty

# Server
destination:      ./_site
exclude:          [".editorconfig", ".gitignore", ".bowerrc", "jshintrc", "bower.json", "config.json", "Gruntfile.js", "package.json", "manifest.cfg", "rules.xml", "node_modules", "bower_components", "README.md", "assets", "less", "dist", "js", "overrides"]
port:             9001

# Custom vars
current_version:  1.0.0
repo:             https://github.com/ade25/

download_source:  https://github.com/twbs/bootstrap/archive/v3.0.0.zip
download_dist:    https://github.com/twbs/bootstrap/releases/download/v3.0.0/bootstrap-3.0.0-dist.zip

blog:             http://blog.getbootstrap.com
expo:             http://expo.getbootstrap.com